# -*- coding: utf-8 -*-
"""Aula 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zUvLl_OUrMgbNi8Y-_mhJJ2PYnkQhWcb

# Verificando o tipo de uma variável
"""

nome = "Eduardo"
idade = 30
peso = 69.5
tem_carro = True

print(type(nome))
print(type(idade))
print(type(peso))
print(type(tem_carro))

print(nome, idade, peso, tem_carro)

"""# Conversões de tipo"""

x = 3.14
y = int(x)

print(y)

texto = "100"
numero = int(texto)
print(numero + 50)

"""# Lendo dados do usuário"""

idade = int(input("Digite sua idade: "))
print(f"Você tem {idade} anos.")
print(f"Daqui 10 anos, você terá {idade + 10} anos.")
print(type(idade))

"""# Operações com números"""

a = float(input("Digite um número: "))
b = float(input("Digite outro número: "))
print(f"Soma: {a + b}")
print(f"Subtração: {a - b}")
print(f"Multiplicação: {a * b}")
print(f"Divisão: {a / b}")

"""# Trabalhando com textos"""

mensagem = "Aprender Python é muito legal!!"

print(mensagem.upper())
print(mensagem.lower())
print(mensagem.title())
print(len(mensagem))

"""# BOOLEANOS"""

tem_dinheiro = True
chovendo = False

print(tem_dinheiro)
print(type(chovendo))

print(5 > 2)
print(10 == 5)
print(10 != 5)

"""# Exercícios"""

nome = input("Digite seu nome: ")
idade = int(input("Digite sua idade: "))
altura = float(input("Digite sua altura: "))
cidade = input("Digite sua cidade: ")

print(f"Olá {nome}! Você tem {idade} anos, tem {altura} de altura e mora em {cidade}. Seja muito bem-vindo ao nosso sistema")

num1 = float(input("Digite o primeito número: "))
num2 = float(input("Digite o segundo número: "))

print(f"Soma: {num1 + num2}")
print(f"Média: {(num1 + num2) / 2}")
print(f"Diferença Absoluta: {abs(num1 - num2)}")

nome = input("Digite seu nome: ")
peso = float(input("Digite seu peso: "))
altura = float(input("Digite sua altura: "))
imc = peso / (altura ** 2)

print(f"Olá {nome}! Seu peso é {peso} e sua altura é {altura}. Sendo assim, podemos calcular seu IMC, que é {imc}.")