# -*- coding: utf-8 -*-
"""Aula 1 - Introdução ao Python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18sjVSsoGpJmpRfIyF-ao8Lb4sAr-kU2x

# Eduardo, 29/10/2025
# Primeira aula em Python
"""

nome = input("Qual o seu nome?")
cidade = input("Em qual cidade você mora?")

print(f"Olá, meu nome é {nome}. Eu moro em {cidade}. Estou aprendendo Python!")

a = 8
b = 2

soma = a + b
multiplicacao = a * b
potencia = a ** b

print(f"O resultado da soma de {a} + {b} é: {soma}")
print(f"O resultado da multiplicação de {a} * {b} é: {multiplicacao}")
print(f"O resultado da potência de {a} ** {b} é: {potencia}")

nome = input("Qual o seu nome? ")
idade = input("Qual a sua idade? ")
altura = input("Qual a sua altura? ")
cidade = input("Em qual cidade você mora? ")

print(f"======= FICHA DO USUÁRIO ========")
print(f"Nome: {nome}")
print(f"Idade: {idade}")
print(f"Altura: {altura}")
print(f"Cidade: {cidade}")